version: '2.1'

services:
  changeme-redis:
    restart: always
    container_name: changeme-redis
    image: redis:alpine
    command: redis-server --requirepass 123456
    ports:
      - "63791:6379"
    volumes:
      - ../../builds/redis/.redis:/data/
