all: true
structname: '{{.InterfaceName}}'
template: testify
packages:
  github.com/beabys/go-template/internal/app:
    config:
      dir: mocks/app
      filename: "{{.InterfaceName}}.go"
  github.com/beabys/go-template/internal/app/config:
    config:
      dir: mocks/app/config
      filename: "{{.InterfaceName}}.go"
  github.com/beabys/go-template/internal/application/example/repository:
    config:
      dir: mocks/application/repository
      filename: "{{.InterfaceName}}.go"
  github.com/beabys/go-template/internal/application/example/handler:
    config:
      dir: mocks/application/handler
      filename: "{{.InterfaceName}}.go"
