all: True
quiet: False
disable-version-string: True
# recursive: True
mockname: "{{.InterfaceName}}"
filename: "{{.MockName}}.go"
# dir: "./{{.InterfaceDirRelative}}/mocks"
with-expecter: True
packages: 
#### app
  github.com/beabys/go-template/internal/app:
    config:
      dir: "mocks/app"
  github.com/beabys/go-template/internal/app/config:
    config:
      dir: "mocks/app/config"
#### api
  github.com/beabys/go-template/internal/api:
    config:
      dir: "mocks/api"
  github.com/beabys/go-template/internal/api/v1:
    config:
      dir: "mocks/api/v1"
#### hello_world
  github.com/beabys/go-template/internal/hello_world:
    config:
      dir: "mocks/hello_world"
  github.com/beabys/go-template/internal/hello_world/repository:
    config:
      dir: "mocks/hello_world/repository"
      