all: True
quiet: False
disable-version-string: True
# recursive: True
mockname: "{{.InterfaceName}}"
filename: "{{.MockName}}.go"
dir: "./{{.InterfaceDirRelative}}/mocks"
with-expecter: True
packages: 
  gitlab.com/beabys/go-template/internal/api:
    config:
      recursive: True
  gitlab.com/beabys/go-template/internal/app:
    config:
      recursive: True
  gitlab.com/beabys/go-template/internal/hello_world:
    config:
      recursive: True
      