openapi: 3.0.1

info:
  title: Go template app
  version: 1.0.0
security:
  - BearerAuth: []
paths:
  /hello:
    get:
      tags:
        - hello-world
      summary: "Helloworld is a default Get method used as example"
      operationId: "HelloWorld"
      responses:
        "200":
          $ref: "#/components/responses/Success"
        "400":
          description: Bad Request
          $ref: "#/components/responses/Fail"
        "404":
          description: Not Found
          $ref: "#/components/responses/Fail"
        default:
          description: Unexpected error
          $ref: "#/components/responses/Fail"
components:
  responses:
    Success:
      description: Success Rest Response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Response"
    Fail:
      description: Fail Rest Response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Response"
  schemas:
    Response:
      type: object
      required:
        - "success"
        - "data"
      properties:
        success:
          type: boolean
        data:
          type: object
