// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ParameterError is an autogenerated mock type for the ParameterError type
type ParameterError struct {
	mock.Mock
}

// Error provides a mock function with given fields:
func (_m *ParameterError) Error() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ParamName provides a mock function with given fields:
func (_m *ParameterError) ParamName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ParamName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewParameterError creates a new instance of ParameterError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParameterError(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParameterError {
	mock := &ParameterError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
