// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	quetzal "gitlab.com/beabys/quetzal"
)

// Application is an autogenerated mock type for the Application type
type Application struct {
	mock.Mock
}

// Recoverer provides a mock function with given fields: _a0
func (_m *Application) Recoverer(_a0 func()) {
	_m.Called(_a0)
}

// Run provides a mock function with given fields:
func (_m *Application) Run() {
	_m.Called()
}

// SetLogger provides a mock function with given fields: _a0
func (_m *Application) SetLogger(_a0 quetzal.Logger) {
	_m.Called(_a0)
}

// Setup provides a mock function with given fields:
func (_m *Application) Setup() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Setup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewApplication creates a new instance of Application. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApplication(t interface {
	mock.TestingT
	Cleanup(func())
}) *Application {
	mock := &Application{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
