// Code generated by mockery. DO NOT EDIT.

package v1

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ServerInterface is an autogenerated mock type for the ServerInterface type
type ServerInterface struct {
	mock.Mock
}

type ServerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ServerInterface) EXPECT() *ServerInterface_Expecter {
	return &ServerInterface_Expecter{mock: &_m.Mock}
}

// HelloWorld provides a mock function with given fields: w, r
func (_m *ServerInterface) HelloWorld(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ServerInterface_HelloWorld_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HelloWorld'
type ServerInterface_HelloWorld_Call struct {
	*mock.Call
}

// HelloWorld is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *ServerInterface_Expecter) HelloWorld(w interface{}, r interface{}) *ServerInterface_HelloWorld_Call {
	return &ServerInterface_HelloWorld_Call{Call: _e.mock.On("HelloWorld", w, r)}
}

func (_c *ServerInterface_HelloWorld_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *ServerInterface_HelloWorld_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *ServerInterface_HelloWorld_Call) Return() *ServerInterface_HelloWorld_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServerInterface_HelloWorld_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *ServerInterface_HelloWorld_Call {
	_c.Call.Return(run)
	return _c
}

// NewServerInterface creates a new instance of ServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServerInterface {
	mock := &ServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
