version: '2.1'

services:
  go-http-template:
    container_name: go-http-template
    image: test-server
    env_file:
      - ../../.env
    restart: always
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    volumes:
      - ../../configs:/etc/config/
