// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/beabys/go-template/internal/domain/example/model"
	mock "github.com/stretchr/testify/mock"
)

// NewHelloWorldRepository creates a new instance of HelloWorldRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHelloWorldRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *HelloWorldRepository {
	mock := &HelloWorldRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HelloWorldRepository is an autogenerated mock type for the HelloWorldRepository type
type HelloWorldRepository struct {
	mock.Mock
}

type HelloWorldRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *HelloWorldRepository) EXPECT() *HelloWorldRepository_Expecter {
	return &HelloWorldRepository_Expecter{mock: &_m.Mock}
}

// GetHelloWorld provides a mock function for the type HelloWorldRepository
func (_mock *HelloWorldRepository) GetHelloWorld(ctx context.Context, id model.HelloWorldID) (*model.HelloWorld, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetHelloWorld")
	}

	var r0 *model.HelloWorld
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.HelloWorldID) (*model.HelloWorld, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.HelloWorldID) *model.HelloWorld); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.HelloWorld)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.HelloWorldID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HelloWorldRepository_GetHelloWorld_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHelloWorld'
type HelloWorldRepository_GetHelloWorld_Call struct {
	*mock.Call
}

// GetHelloWorld is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *HelloWorldRepository_Expecter) GetHelloWorld(ctx interface{}, id interface{}) *HelloWorldRepository_GetHelloWorld_Call {
	return &HelloWorldRepository_GetHelloWorld_Call{Call: _e.mock.On("GetHelloWorld", ctx, id)}
}

func (_c *HelloWorldRepository_GetHelloWorld_Call) Run(run func(ctx context.Context, id model.HelloWorldID)) *HelloWorldRepository_GetHelloWorld_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.HelloWorldID))
	})
	return _c
}

func (_c *HelloWorldRepository_GetHelloWorld_Call) Return(helloWorld *model.HelloWorld, err error) *HelloWorldRepository_GetHelloWorld_Call {
	_c.Call.Return(helloWorld, err)
	return _c
}

func (_c *HelloWorldRepository_GetHelloWorld_Call) RunAndReturn(run func(ctx context.Context, id model.HelloWorldID) (*model.HelloWorld, error)) *HelloWorldRepository_GetHelloWorld_Call {
	_c.Call.Return(run)
	return _c
}

// SaveHelloWorld provides a mock function for the type HelloWorldRepository
func (_mock *HelloWorldRepository) SaveHelloWorld(ctx context.Context, helloWorld *model.HelloWorld) error {
	ret := _mock.Called(ctx, helloWorld)

	if len(ret) == 0 {
		panic("no return value specified for SaveHelloWorld")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.HelloWorld) error); ok {
		r0 = returnFunc(ctx, helloWorld)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// HelloWorldRepository_SaveHelloWorld_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveHelloWorld'
type HelloWorldRepository_SaveHelloWorld_Call struct {
	*mock.Call
}

// SaveHelloWorld is a helper method to define mock.On call
//   - ctx
//   - helloWorld
func (_e *HelloWorldRepository_Expecter) SaveHelloWorld(ctx interface{}, helloWorld interface{}) *HelloWorldRepository_SaveHelloWorld_Call {
	return &HelloWorldRepository_SaveHelloWorld_Call{Call: _e.mock.On("SaveHelloWorld", ctx, helloWorld)}
}

func (_c *HelloWorldRepository_SaveHelloWorld_Call) Run(run func(ctx context.Context, helloWorld *model.HelloWorld)) *HelloWorldRepository_SaveHelloWorld_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.HelloWorld))
	})
	return _c
}

func (_c *HelloWorldRepository_SaveHelloWorld_Call) Return(err error) *HelloWorldRepository_SaveHelloWorld_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *HelloWorldRepository_SaveHelloWorld_Call) RunAndReturn(run func(ctx context.Context, helloWorld *model.HelloWorld) error) *HelloWorldRepository_SaveHelloWorld_Call {
	_c.Call.Return(run)
	return _c
}
