// Code generated by mockery. DO NOT EDIT.

package repository

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "gitlab.com/beabys/go-template/internal/domain/model"
)

// RepositoryIntereface is an autogenerated mock type for the RepositoryIntereface type
type RepositoryIntereface struct {
	mock.Mock
}

type RepositoryIntereface_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryIntereface) EXPECT() *RepositoryIntereface_Expecter {
	return &RepositoryIntereface_Expecter{mock: &_m.Mock}
}

// SaveHelloWorld provides a mock function with given fields: _a0, _a1
func (_m *RepositoryIntereface) SaveHelloWorld(_a0 context.Context, _a1 *model.HelloWorld) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SaveHelloWorld")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.HelloWorld) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryIntereface_SaveHelloWorld_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveHelloWorld'
type RepositoryIntereface_SaveHelloWorld_Call struct {
	*mock.Call
}

// SaveHelloWorld is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *model.HelloWorld
func (_e *RepositoryIntereface_Expecter) SaveHelloWorld(_a0 interface{}, _a1 interface{}) *RepositoryIntereface_SaveHelloWorld_Call {
	return &RepositoryIntereface_SaveHelloWorld_Call{Call: _e.mock.On("SaveHelloWorld", _a0, _a1)}
}

func (_c *RepositoryIntereface_SaveHelloWorld_Call) Run(run func(_a0 context.Context, _a1 *model.HelloWorld)) *RepositoryIntereface_SaveHelloWorld_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.HelloWorld))
	})
	return _c
}

func (_c *RepositoryIntereface_SaveHelloWorld_Call) Return(_a0 error) *RepositoryIntereface_SaveHelloWorld_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryIntereface_SaveHelloWorld_Call) RunAndReturn(run func(context.Context, *model.HelloWorld) error) *RepositoryIntereface_SaveHelloWorld_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositoryIntereface creates a new instance of RepositoryIntereface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryIntereface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryIntereface {
	mock := &RepositoryIntereface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
