apiVersion: v1
kind: ConfigMap
metadata:
  name: go-template-configmap
data:
  config.yaml: |
    stage: development
    grpc:
        port: 3001
    http:
        host: 127.0.0.1
        port: 3001
        api_prefix: "/v1"
    db:
        user: user
        password: password
        host: host.minikube.internal
        port: 33061
        name: go-template
        log_sql: true
        max_idle_connections: 5
        max_open_conn: 5
        connection_max_lifetime_seconds: 10
    redis:
        password: password
        host: host.minikube.internal
        port: 63791
        database: 0
