apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-template-deployment
  labels:
    app: go-template
spec:
  selector:
    matchLabels:
      app: go-template
  replicas: 2
  template:
    spec:
      containers:
      - name: go-template
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: '50m'
            memory: '50Mi'
          limits:
            cpu: '150m'
            memory: '200Mi'
