apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-http-template-hpa
spec:
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
