apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-template-deployment
  labels:
    app: go-template
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-template
  template:
    metadata:
      labels:
        app: go-template
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 10000
        runAsGroup: 10000
        runAsNonRoot: true
        fsGroup: 20000
      containers:
      - name: go-template
        image: go-template
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsUser: 10000
          runAsGroup: 10000
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        ports:
        - protocol: TCP
          containerPort: 3001
        env:
        - name: CONFIG_FILE
          valueFrom:
            configMapKeyRef:
              name: go-template-config
              key: config_file_path
        resources:
            requests:
              cpu: '50m'
              memory: '50Mi'
            limits:
              cpu: '150m'
              memory: '200Mi'
        volumeMounts:
          - mountPath: "/etc/config"
            name: go-template-config-volume
      volumes:
        - name: go-template-config-volume
          configMap:
            name: go-template-configmap

