// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package app

import (
	"context"

	"github.com/beabys/go-template/internal/app/config"
	"github.com/beabys/go-template/pkg/logger"
	mock "github.com/stretchr/testify/mock"
)

// NewApplication creates a new instance of Application. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApplication(t interface {
	mock.TestingT
	Cleanup(func())
}) *Application {
	mock := &Application{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Application is an autogenerated mock type for the Application type
type Application struct {
	mock.Mock
}

type Application_Expecter struct {
	mock *mock.Mock
}

func (_m *Application) EXPECT() *Application_Expecter {
	return &Application_Expecter{mock: &_m.Mock}
}

// Recoverer provides a mock function for the type Application
func (_mock *Application) Recoverer(fn func()) {
	_mock.Called(fn)
	return
}

// Application_Recoverer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recoverer'
type Application_Recoverer_Call struct {
	*mock.Call
}

// Recoverer is a helper method to define mock.On call
//   - fn
func (_e *Application_Expecter) Recoverer(fn interface{}) *Application_Recoverer_Call {
	return &Application_Recoverer_Call{Call: _e.mock.On("Recoverer", fn)}
}

func (_c *Application_Recoverer_Call) Run(run func(fn func())) *Application_Recoverer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func()))
	})
	return _c
}

func (_c *Application_Recoverer_Call) Return() *Application_Recoverer_Call {
	_c.Call.Return()
	return _c
}

func (_c *Application_Recoverer_Call) RunAndReturn(run func(fn func())) *Application_Recoverer_Call {
	_c.Run(run)
	return _c
}

// Run provides a mock function for the type Application
func (_mock *Application) Run(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Application_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Application_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - context1
func (_e *Application_Expecter) Run(context1 interface{}) *Application_Run_Call {
	return &Application_Run_Call{Call: _e.mock.On("Run", context1)}
}

func (_c *Application_Run_Call) Run(run func(context1 context.Context)) *Application_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Application_Run_Call) Return(err error) *Application_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Application_Run_Call) RunAndReturn(run func(context1 context.Context) error) *Application_Run_Call {
	_c.Call.Return(run)
	return _c
}

// SetLogger provides a mock function for the type Application
func (_mock *Application) SetLogger(logger1 logger.Logger) {
	_mock.Called(logger1)
	return
}

// Application_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type Application_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger1
func (_e *Application_Expecter) SetLogger(logger1 interface{}) *Application_SetLogger_Call {
	return &Application_SetLogger_Call{Call: _e.mock.On("SetLogger", logger1)}
}

func (_c *Application_SetLogger_Call) Run(run func(logger1 logger.Logger)) *Application_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(logger.Logger))
	})
	return _c
}

func (_c *Application_SetLogger_Call) Return() *Application_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *Application_SetLogger_Call) RunAndReturn(run func(logger1 logger.Logger)) *Application_SetLogger_Call {
	_c.Run(run)
	return _c
}

// Setup provides a mock function for the type Application
func (_mock *Application) Setup(appConfig config.AppConfig, cancelFunc context.CancelFunc) error {
	ret := _mock.Called(appConfig, cancelFunc)

	if len(ret) == 0 {
		panic("no return value specified for Setup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(config.AppConfig, context.CancelFunc) error); ok {
		r0 = returnFunc(appConfig, cancelFunc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Application_Setup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setup'
type Application_Setup_Call struct {
	*mock.Call
}

// Setup is a helper method to define mock.On call
//   - appConfig
//   - cancelFunc
func (_e *Application_Expecter) Setup(appConfig interface{}, cancelFunc interface{}) *Application_Setup_Call {
	return &Application_Setup_Call{Call: _e.mock.On("Setup", appConfig, cancelFunc)}
}

func (_c *Application_Setup_Call) Run(run func(appConfig config.AppConfig, cancelFunc context.CancelFunc)) *Application_Setup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(config.AppConfig), args[1].(context.CancelFunc))
	})
	return _c
}

func (_c *Application_Setup_Call) Return(err error) *Application_Setup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Application_Setup_Call) RunAndReturn(run func(appConfig config.AppConfig, cancelFunc context.CancelFunc) error) *Application_Setup_Call {
	_c.Call.Return(run)
	return _c
}
