version: '2.1'

services:
  go-http-template:
    extends:
      file: app/docker-compose.yml
      service: go-http-template
    env_file:
      - ../.env
    networks:
      - go-http-template-service
    depends_on: 
      - go-http-template-db
  go-http-template-db:
    extends:
      file: mysql/docker-compose.yml
      service: go-http-template-db
    volumes:
        # - ../builds/mysql/dump:/docker-entrypoint-initdb.d
        - ../builds/mysql/.mariadb:/var/lib/mysql
    networks:
      - go-http-template-service
  go-http-template-redis:
    extends:
      file: redis/docker-compose.yml
      service: go-http-template-redis
    volumes:
      - ../builds/redis/.redis:/data/
    networks:
      - go-http-template-service
networks:
  go-http-template-service:
    driver: bridge
