version: '2.1'

services:
  changeme-app:
    extends:
      file: app/docker-compose.yml
      service: changeme-app
    env_file:
      - ../.env
    networks:
      - changeme-service
    depends_on: 
      - changeme-db
  changeme-db:
    extends:
      file: mysql/docker-compose.yml
      service: changeme-db
    volumes:
        # - ../builds/mysql/dump:/docker-entrypoint-initdb.d
        - ../builds/mysql/.mariadb:/var/lib/mysql
    networks:
      - changeme-service
  changeme-redis:
    extends:
      file: redis/docker-compose.yml
      service: changeme-redis
    volumes:
      - ../builds/redis/.redis:/data/
    networks:
      - changeme-service
networks:
  changeme-service:
    driver: bridge
