// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "gitlab.com/beabys/go-http-template/internal/domain/model"
)

// HelloWorldIntereface is an autogenerated mock type for the HelloWorldIntereface type
type HelloWorldIntereface struct {
	mock.Mock
}

// GetHelloWorld provides a mock function with given fields: _a0
func (_m *HelloWorldIntereface) GetHelloWorld(_a0 context.Context) (*model.HelloWorld, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetHelloWorld")
	}

	var r0 *model.HelloWorld
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*model.HelloWorld, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *model.HelloWorld); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.HelloWorld)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHelloWorldIntereface creates a new instance of HelloWorldIntereface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHelloWorldIntereface(t interface {
	mock.TestingT
	Cleanup(func())
}) *HelloWorldIntereface {
	mock := &HelloWorldIntereface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
