version: '2.1'

services:
  go-http-template-db:
    image: mariadb
    container_name: go-http-template-db
    ports: 
        - "33061:3306"
    restart: always
    environment:
        MYSQL_DATABASE: go-http-template-db
        MYSQL_USER: dev
        MYSQL_PASSWORD: 123456
        MYSQL_ROOT_PASSWORD: 123456
    volumes:
        # - ../../builds/mysql/dump:/docker-entrypoint-initdb.d
        - ../../builds/mysql/.mariadb/mysql:/var/lib/mysql
