// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ApiServer is an autogenerated mock type for the ApiServer type
type ApiServer struct {
	mock.Mock
}

// Run provides a mock function with given fields: _a0, _a1
func (_m *ApiServer) Run(_a0 context.Context, _a1 context.CancelFunc) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, context.CancelFunc) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewApiServer creates a new instance of ApiServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApiServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ApiServer {
	mock := &ApiServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
