// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/beabys/go-template/internal/application/example/command"
	mock "github.com/stretchr/testify/mock"
)

// NewExampleServiceHandler creates a new instance of ExampleServiceHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExampleServiceHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExampleServiceHandler {
	mock := &ExampleServiceHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ExampleServiceHandler is an autogenerated mock type for the ExampleServiceHandler type
type ExampleServiceHandler struct {
	mock.Mock
}

type ExampleServiceHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *ExampleServiceHandler) EXPECT() *ExampleServiceHandler_Expecter {
	return &ExampleServiceHandler_Expecter{mock: &_m.Mock}
}

// GetHelloWorld provides a mock function for the type ExampleServiceHandler
func (_mock *ExampleServiceHandler) GetHelloWorld(ctx context.Context, req *command.GetHelloWorldRequest) (*command.GetHelloWorldResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetHelloWorld")
	}

	var r0 *command.GetHelloWorldResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *command.GetHelloWorldRequest) (*command.GetHelloWorldResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *command.GetHelloWorldRequest) *command.GetHelloWorldResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*command.GetHelloWorldResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *command.GetHelloWorldRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExampleServiceHandler_GetHelloWorld_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHelloWorld'
type ExampleServiceHandler_GetHelloWorld_Call struct {
	*mock.Call
}

// GetHelloWorld is a helper method to define mock.On call
//   - ctx
//   - req
func (_e *ExampleServiceHandler_Expecter) GetHelloWorld(ctx interface{}, req interface{}) *ExampleServiceHandler_GetHelloWorld_Call {
	return &ExampleServiceHandler_GetHelloWorld_Call{Call: _e.mock.On("GetHelloWorld", ctx, req)}
}

func (_c *ExampleServiceHandler_GetHelloWorld_Call) Run(run func(ctx context.Context, req *command.GetHelloWorldRequest)) *ExampleServiceHandler_GetHelloWorld_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*command.GetHelloWorldRequest))
	})
	return _c
}

func (_c *ExampleServiceHandler_GetHelloWorld_Call) Return(getHelloWorldResponse *command.GetHelloWorldResponse, err error) *ExampleServiceHandler_GetHelloWorld_Call {
	_c.Call.Return(getHelloWorldResponse, err)
	return _c
}

func (_c *ExampleServiceHandler_GetHelloWorld_Call) RunAndReturn(run func(ctx context.Context, req *command.GetHelloWorldRequest) (*command.GetHelloWorldResponse, error)) *ExampleServiceHandler_GetHelloWorld_Call {
	_c.Call.Return(run)
	return _c
}
